# Generated by Django 3.2.6 on 2021-08-20 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('cnpj', models.CharField(max_length=80, unique=True, verbose_name='CNPJ')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('logo', stdimage.models.StdImageField(upload_to='empresas/logo', verbose_name='Logo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
