# Generated by Django 3.2.6 on 2021-08-20 18:21

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=stdimage.models.StdImageField(upload_to='medias/empresas/logo', verbose_name='Logo'),
        ),
    ]
